Improve status output.

diff --git a/root.test/usr/local/sbin/test-runner b/root.test/usr/local/sbin/test-runner
--- a/root.test/usr/local/sbin/test-runner
+++ b/root.test/usr/local/sbin/test-runner
@@ -1,13 +1,6 @@
 #!/usr/bin/env bash
 set -e
 
-function die()
-{
-    echo "::error::$1"
-    echo "------------------------------------------------------------------------------------------------------------------------"
-    exit 1
-}
-
 cat << END
 ------------------------------------------------------------------------------------------------------------------------
                                  _                    _            _                                    
@@ -21,11 +14,18 @@ cat << END
  
                https://github.com/hacking-gentoo/gentoo                             (c) 2019 Max Hacking 
 ------------------------------------------------------------------------------------------------------------------------
+$(set)
+------------------------------------------------------------------------------------------------------------------------
+$(shopt)
+------------------------------------------------------------------------------------------------------------------------
 END
-set
-echo "------------------------------------------------------------------------------------------------------------------------"
-shopt
-echo "------------------------------------------------------------------------------------------------------------------------"
+
+function die()
+{
+    echo "::error::$1"
+    echo "------------------------------------------------------------------------------------------------------------------------"
+    exit 1
+}
 
 # Check for a GITHUB_WORKSPACE env variable
 [[ -z "${GITHUB_WORKSPACE}" ]] && die "Must set GITHUB_WORKSPACE in env"
